# Generated by Django 6.1.1 on 2026-09-21 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název parkoviště')),
                ('floor', models.IntegerField(default=0, verbose_name='Patro')),
            ],
            options={
                'verbose_name': 'Parkoviště',
                'verbose_name_plural': 'Parkoviště',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Číslo místa')),
                ('spot_type', models.CharField(choices=[('NORMAL', 'Běžné'), ('DISABLED_ONLY', 'Vyhrazeno pro ZTP'), ('EV_ONLY', 'Nabíjecí stanice (EV)')], default='NORMAL', max_length=20, verbose_name='Typ místa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní pro rezervace')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='rezervace.parkinglot', verbose_name='Parkoviště')),
            ],
            options={
                'verbose_name': 'Parkovací místo',
                'verbose_name_plural': 'Parkovací místa',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum rezervace')),
                ('start_time', models.TimeField(verbose_name='Od')),
                ('end_time', models.TimeField(verbose_name='Do')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rezervace.parkingspot', verbose_name='Parkovací místo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Zaměstnanec')),
            ],
            options={
                'verbose_name': 'Rezervace',
                'verbose_name_plural': 'Rezervace',
            },
        ),
    ]
