@startuml
title Activity diagram. Proces of reservation by employee.

skinparam ActivityBackgroundColor LightGray
skinparam ActivityBorderColor Black
skinparam defaultTextAlignment center

' Definice plaveckých drah
|Zaměstnanec|
|Systém (Django)|

|Zaměstnanec|
start
:Výběr data a času pro parkování;

|Systém (Django)|
:Dotaz do databáze na existující\nrezervace pro zadaný termín;
:Zobrazení volných a obsazených míst;

|Zaměstnanec|
:Vybrání volného místa;
:Odeslání rezervačního formuláře;

|Systém (Django)|
' Rozhodovací uzel pro kontrolu dostupnosti
if (Je vybrané místo stále volné?) then (Ano)
    :Uložení nového objektu\nReservation do databáze;
    :Příprava potvrzovací zprávy;
else (Ne - někdo byl rychlejší)
    :Vygenerování chybové hlášky;
endif

' Společné sjednocení čistě na frontendu (u zaměstnance)
|Zaměstnanec|
:Zobrazení výsledku akce\n(Úspěšná rezervace / Nový výběr);
stop
@enduml